"""
Output Agent — assembles all approved documentation into a single
Markdown file, organized by element type.
"""

from pathlib import Path
from agents.base_agent import BaseAgent
from tools.code_tools import write_markdown
from config import MODEL, DOC_WRITER_MODEL, REVIEWER_MODEL, FACT_CHECKER_MODEL

HEADER_TEMPLATE = """# Documentation: `{filename}`

> Auto-generated by the multi-agent documentation workflow.
> Model: {model} | Generated: {timestamp}

---

"""

SECTION_ORDER = ["class", "method", "function"]
SECTION_TITLES = {
    "class": "Classes",
    "method": "Methods",
    "function": "Functions",
}


class OutputAgent(BaseAgent):
    def __init__(self, memory):
        super().__init__("OutputAgent", memory)

    def run(self):
        from datetime import datetime

        doc = self.memory.file_documentation
        if not doc:
            self.log("No documentation to write.")
            return

        filename = Path(self.memory.target_file).name
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        model_display = DOC_WRITER_MODEL or MODEL

        content = HEADER_TEMPLATE.format(filename=filename, timestamp=timestamp, model=model_display)
        summary = getattr(self.memory, "file_summary", None)
        if summary:
            content += f"## Summary\n\n{summary.strip()}\n\n---\n\n"

        content += doc.strip() + "\n"

        write_markdown(content, self.memory.output_path)
        self.log(f"Markdown written to: {self.memory.output_path}")
